[joomla] Docker images updates - 2021-08-19
GoogleCloudPlatform/joomla-docker pull request #24
Opened 2021-08-19 12:58 UTC by EugeneKorolevich

2021-09-06 12:21 UTC, ovk6 requested changes

2021-09-06 12:21 UTC, ovk6 commented on versions.yaml
> +- dir: 4/php7/debian9/apache/4/
`4/php7/debian9/apache/4.0`

2021-09-06 12:21 UTC, ovk6 commented on versions.yaml
> +- dir: 3/php7/debian9/apache/3.10/
remove last /

2021-09-06 12:21 UTC, ovk6 commented on versions.yaml
> +- dir: 3/php7/debian9/apache/3.9/
remove last /

2021-09-06 12:21 UTC, ovk6 commented on versions.yaml
> +
remove newline

2021-09-06 13:18 UTC, EugeneKorolevich commented on versions.yaml
> +- dir: 4/php7/debian9/apache/4/
done

2021-09-06 13:18 UTC, EugeneKorolevich commented on versions.yaml
> +- dir: 3/php7/debian9/apache/3.10/
done

2021-09-06 13:18 UTC, EugeneKorolevich commented on versions.yaml
> +- dir: 3/php7/debian9/apache/3.9/
done

2021-09-06 13:19 UTC, EugeneKorolevich commented on versions.yaml
> +
done

2021-09-13 12:47 UTC, armandomiani commented
@googlebot I consent.

2021-09-14 09:14 UTC, ovk6 approved these changes

2021-09-14 09:27 UTC, merged